"""init

Revision ID: 39ce64a43883
Revises: dd33cb03d01f
Create Date: 2023-01-25 02:47:23.002624

"""

# revision identifiers, used by Alembic.
revision = '39ce64a43883'
down_revision = 'dd33cb03d01f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
