"""init

Revision ID: 591a739a4d1b
Revises: 67877439a512
Create Date: 2023-01-25 04:24:03.893505

"""

# revision identifiers, used by Alembic.
revision = '591a739a4d1b'
down_revision = '67877439a512'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
