"""init

Revision ID: 67877439a512
Revises: 39ce64a43883
Create Date: 2023-01-25 04:20:10.022700

"""

# revision identifiers, used by Alembic.
revision = '67877439a512'
down_revision = '39ce64a43883'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
