"""init

Revision ID: 7ca16901b0d0
Revises: 591a739a4d1b
Create Date: 2023-01-25 04:34:08.374321

"""

# revision identifiers, used by Alembic.
revision = '7ca16901b0d0'
down_revision = '591a739a4d1b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
