"""init

Revision ID: a86c8da72c19
Revises: 7ca16901b0d0
Create Date: 2023-01-25 04:55:41.806577

"""

# revision identifiers, used by Alembic.
revision = 'a86c8da72c19'
down_revision = '7ca16901b0d0'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
